config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :users, only: [:new, :create, :show]
  resources :tasks
  root to:'sessions#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  #validates :name, :content, :status, :priority, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  paginates_per 3
  #belongs_to:user
  validates :name, presence: true
  validates :content, presence: true
  validates :status, presence: true
  validates :priority, presence: true
  validates :beginning_date, presence: true
  validates :ending_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, presence: true
    validates :email, presence: true, uniqueness: true
    has_secure_password
    #has_many :tasks

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
    def self.search(term)
        if term
          where('status LIKE ?', "%#{term}%").order('id DESC')
          where('priority LIKE ?', "%#{term}%").order('id DESC')
        else
          order('id DESC') 
        end
      end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

      def create
        user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to tasks_path
    else
      flash.now[:danger] = 'Login failed'
      render 'new'
    end

    end
  def new
    
  end
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'You logged out'
    redirect_to new_session_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    # @tasks = Task.search(params[:term])
     @tasks = Task.all
     @tasks = Task.all.order("created_at DESC")
    
    @tasks = if params[:term]
      Task.where('priority LIKE ? or status LIKE ?', "%#{params[:term]}%", "%#{params[:term]}%").page params[:page]
    else
     # @tasks = Task.order('name').page params[:page]
      Task.order('priority DESC').page(params[:page])
    end
  end
  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
def search
  @task =task.search(params[:search])
end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :content, :status, :priority, :beginning_date, :ending_date , :term)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end
    def index
      @users = User.all
    end
    def create
        @user = User.new(user_params) 
        if @user.save
         redirect_to user_path(@user.id)
          else
            render 'new'
        end
    end
        
  def show
    @user = User.find(params[:id])
  end  
  def edit
    @user= User.find(params[:id])
  end
  def update
    @user= User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:notice] = 'user updated!'
      redirect_to root_path
    else
      flash[:error] = 'Failed to edit user!'
      render :edit
    end
  end
  # DELETE method for deleting a product from database based on id
  def destroy
    @user = User.find(params[:id])
    if @user.delete
      flash[:notice] = 'user deleted!'
      redirect_to root_path
    else
      flash[:error] = 'Failed to delete this user!'
      render :destroy
    end
  end
  # we used strong parameters for the validation of params
  # def user_params
  #   params.require(:product).permit(:name, :email :password, :password_confirmation, :title)
  # end
 # end
 def current_user
  User.find_by(id: session[:user_id])
 endsss
  end
    private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    def logged_in?
        current_user.present?
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Everleafapp</title>
   
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body> 
  <nav class="navbar navbar-light">
  <I><a class="navbar-brand">Welcome to Everleaf co... LTD </a></I>
  <form class="form-inline">
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>
  
  <% if logged_in? %>
    <%= link_to 'Home', tasks_path %>&nbsp &nbsp
    <%= link_to "Profile", user_path(current_user.id) %>&nbsp &nbsp
    <%= link_to "Logout", session_path(current_user.id), method: :delete %>
  <% else %>
    <%= link_to "Sign up", new_user_path %>&nbsp &nbsp
    <%= link_to "Login", new_session_path %>
  <% end %>
  </form>
</nav>


    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :priority %>
    <%= form.text_field :priority %>
  </div>

  <div class="field">
    <%= form.label :beginning_date %>
    <%= form.datetime_select :beginning_date %>
  </div>

  <div class="field">
    <%= form.label :ending_date %>
    <%= form.datetime_select :ending_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>
<%= render 'form', task: @task %>
<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<% if logged_in? %>
<p id="notice"><%= notice %></p>
<h1>Tasks</h1>
<div class="page"
<%= paginate @tasks %> 
<nav class= "search">
<%= form_tag(tasks_path, method: :get) do %>
  <%= text_field_tag :term, params[:term] %>
  <%= submit_tag 'Search', name: nil %>
  </nav>
<% end %>
<b><%= t('view.sample') %></b><br><br>
<table>
  <thead>
    <tr>
      <th><%= t('view.name') %></th>
      <th><%= t('view.content') %></th>
      <th><%= t('view.status') %></th>
      <th><%= t('view.priority') %></th>
      <th><%= t('view.Beginning date') %></th>
      <th><%= t('view.Ending date') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.content %></td>
        <td><%= task.status %></td>
        <td><%= task.priority %></td>
        <td><%= task.beginning_date %></td>
        <td><%= task.ending_date %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>
<%= link_to 'New Task', new_task_path %>

<% end %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>
<b><%= t('view.sample') %></b>
<br><br>
<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @task.content %>
</p>

<p>
  <strong>Status:</strong>
  <%= @task.status %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @task.priority %>
</p>

<p>
  <strong>Beginning date:</strong>
  <%= @task.beginning_date %>
</p>

<p>
  <strong>Ending date:</strong>
  <%= @task.ending_date %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Users</h1>
<table>
 <thead>
   <tr>
     <th>name</th>
     <th>email</th>
     <th colspan="2"></th>
   </tr>
 </thead>
 <tbody>
   <% @users.each do |user| %>
     <tr>
       <td><%= link_to user.name, user %></td>
       <td><%= user.email %></td>

       <div>
       <td><%= link_to 'Edit', edit_user_path(user) %></td>
       <td>
        <%= link_to 'show', user_path(user) %>
    </td>
       <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
     </tr>
     </div>
   <% end %>
 </tbody>
</table>
<br>
<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb

<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>page's</h1>
<div class="container">
<h3>Added user</h3>
<div>
<label>user name:</label>
<%= @user.name %>
</div>
<div>
<label>email:</label>
<%= @user.email %>
</div>
<div>
<%= link_to 'new task',new_task_path %><br>
<%= link_to 'back', {controller: 'users',action: 'index'} %>
</div>
</div>




<p>email address: <%= @user.email %></p>